#!/usr/bin/env python
""" This takes the pub_list.html file generated by Zotero and turns
    it into a suitable pub_list.yml that can be used in publist.yml."""

import os

BASE_DATA_DIR = "/home/kevin/PROJECTS/BioAIgroup.github.io/_data/"


#
# Example formatted Zotero data entry input ...
#
#   <div class="csl-entry">Bentham, Robert B., Kevin Bryson, and Gyorgy Szabadkai.
#   ‘Biclustering Analysis of Co-Regulation Patterns in Nuclear-Encoded Mitochondrial Genes and Metabolic Pathways’.
#   In <i>Cancer Metabolism</i>, edited by Majda Haznadar, 1928:469–78. Methods in Molecular Biology. New York, NY: Springer New York, 2019.
#   <a href="https://doi.org/10.1007/978-1-4939-9027-6_24">https://doi.org/10.1007/978-1-4939-9027-6_24</a>. 
# (All given as single lines ...)
#
# Example Jekyll yml data entry output ...
# (Different flags initially set to zero and activated manually.)
#
# - title: "MCbiclust: A Novel Algorithm to Discover Large-Scale Functionally Related Gene Sets from Massive Transcriptomics Data Collections"
#   image: Multistate_gene_clusters_1500.png
#   description: MCbiclust is a biclustering approach that can discover hidden patterns contained in large biological archives of transcriptomics data.
#   description_long: MCbiclust is a biclustering approach that can discover hidden patterns contained in large biological archives of transcriptomics data.
#   authors: Bentham, Robert B., Kevin Bryson, and Gyorgy Szabadkai
#   link:
#     url: https://doi.org/10.1093/nar/gkx590
#     display: Nucleic Acids Research 45, no. 15, 8712–30.
#   highlight: 1
#   genomics: 0
#   transcriptomics: 1
#

import re


print(os.getcwd())

with open(BASE_DATA_DIR + "pub_list.html") as file_in:
    with open(BASE_DATA_DIR + "pub_list.yml", "w") as file_out:
        for line in file_in:

            # Note special UNICODE character used for: ‘ (unicode symbol 2018) and ’ (unicode symbol 2019).
            match = re.search(u"<div class=\"csl-entry\">(.+)‘(.+)’\. (.+)<a href=\"(.+)\"", line)

            if (match):
                file_out.write(f'- title: "{match.group(2)}"\n')
                file_out.write(f'  image: XXX.png\n')
                file_out.write(f'  description: "YYY"\n')
                file_out.write(f'  authors: "{match.group(1)}"\n')
                file_out.write(f'  link:\n')
                file_out.write(f'    url: "{match.group(4)}"\n')
                file_out.write(f'    display: "{match.group(3)}"\n')
                file_out.write(f'  highlight: 0\n')
                file_out.write(f'  ml_ai: 0\n')
                file_out.write(f'  precision_medicine: 0\n')
                file_out.write(f'  genomics: 0\n')
                file_out.write(f'  transcriptomics: 0\n')
                file_out.write(f'  proteomics: 0\n')
                file_out.write(f'  metabolomics: 0\n\n\n')
                file_out.write(f'  sysbio_integration: 0\n\n\n')
